import {
  AlertTriangle,
  ArrowRight,
  Bell,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Home,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  Droplet,
  Users,
  BarChart3,
  Activity,
  AlertCircle,
  ThumbsUp,
  ThumbsDown,
  ExternalLink,
  LogOut,
} from "lucide-react"

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  home: Home,
  notification: Bell,
  food: Pizza,
  nutrition: Activity,
  water: Droplet,
  vulnerability: Users,
  agriculture: FileText,
  livestock: File,
  market: BarChart3,
  alert: AlertCircle,
  approve: ThumbsUp,
  reject: ThumbsDown,
  externalLink: ExternalLink,
  logout: LogOut,
  check: Check,
}

